### ISSUE TITLE
Memory Problems in app_library

### ISSUE THREAD

**Issue by marekventur** [emfcamp/Mk3-Firmware#71]
How to replicate: Go to the home screen, then open the app library and try to download some apps. You will run out of memory here. Running the app library by itself (not through the home screen) works.

Basically we seem to be hanging on to some references on the home screen that we don't need anymore. (How much? Possible candidates?)

- Identify bits that are kept in memory from the homescreen
- Minimise the memory usage of the app_library
- Other ideas?

PRs/comments welcome!

**Comment by marekventur** [comment]
Tools for debugging: 
```
import gc
gc.collect()
print("memory available: %d" % gc.mem_free())
```

**Comment by marekventur** [comment]
Some numbers:

```
app_library run through home/quick_launch:
on start : 22064 free

pyboard.py (or other means for running the app library directly without the home screen)
on start pyboard.py: 34256 free
on start when download starts: 25200 free
```

That means:
1) We could potentially save up to 9056 in the app library download process
2) We could potentially save up to 12192 by freeing more memory once the home app starts another app

Potential solutions:
* Don't make the functions for the different screens in the app_library recursive so memory can be freed

**Comment by Giannie** [comment]
I have made a pull request that could be used to help with this issue. I have included a method of registering an app to be run as main.py temporarily.  This can allow larger apps to make use of all available memory. It requires that the app exits by resetting the board.

https://github.com/emfcamp/Mk3-Firmware/pull/77

**Comment by mattbrejza** [comment]
I did start doing this a different way - by saving the app to run on boot in the battery backed RAM rather than the file system, however its not finished, and will require more RAM since the library it will be in will need to be imported.

I've merged your change, however we may change it to use RAM later since this is probably a neater solution.

Thanks for your contribution.

**Comment by Jonty** [comment]
This is absolutely not fixed yet.

**Comment by Giannie** [comment]
My commit certainly does not fix this issue. I'd be willing to try to rewrite a bit of it to make use of my change, but I doubt it's the most elegant solution.

**Comment by mattbrejza** [comment]
Also, boot.py gets overwritten on a full reset, this should really get moved to apps/home/main.py instead

**Comment by Giannie** [comment]
Moved as suggested. Slightly less effective in terms of memory saving I think, but still better.

**Comment by Giannie** [comment]
If the code is run from apps/home/main.py, gc.mem_free() gives 55744, while if we are able to run a script as the main script from boot.py as I originally suggested then we get 62992.

Is there any way we could include this in boot.py instead of apps/home/main.py? That's a pretty significant memory saving for larger apps.

For me it makes the difference between the text game we're working on working well or not.

I also think it offers a very nice mechanism for people to take control of the main script that the board runs.

**Comment by marekventur** [comment]
I agree with @Giannie on the original idea of having the "what to run" code in boot.py. 

We can update the boot.py bundled with the micropython firmware and add some logic to the app_library to update it along with the lib folder. That way after either two app_store updates or a factory reset badges should have the new code. If we want it with one update we could have some special checksum checks in the home app. 

It was a bit of an oversight to not have boot.py checked for updates in the first place, sorry.

**Comment by Giannie** [comment]
In which case, I think the original commit should function for the boot.py code: https://github.com/emfcamp/Mk3-Firmware/pull/77/commits/07e666c2594375969b9c6040e5fd925a85676148

Although it should probably print the exception on failure rather than passing as I did for some reason.

**Comment by mattbrejza** [comment]
this quick change saves 6k more RAM, but still 2k short of how much RAM is available if run directly from boot.py

https://github.com/emfcamp/Mk3-Firmware/commit/65984ee691af8f96d867f74cc042857eadc78ca9

Running directly from the boot.py would be the neatest way, but I'm not sure its the best seeing some hackery might be required to update that file
